# Cloudflare Pages configuration
name = "fysp-dev-website"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

# Cloudflare Workers AI binding
[ai]
binding = "AI"

[[kv_namespaces]]
binding = "AI_CACHE"
id = "9f5c234e00074f8f9ebd08f6a785e840"
preview_id = "7d27282d6be94a05aa89d3750c092fe5"

[vars]
ENABLED_PROJECTS = "3d,ai,data"
ENABLED_PROJECT_DEMOS = "3d,ai"

[env.preview.vars]
ENABLED_PROJECTS = "3d,ai,blockchain"
ENABLED_PROJECT_DEMOS = "3d,ai"

[env.production.vars]
ENABLED_PROJECTS = "3d,ai"
ENABLED_PROJECT_DEMOS = "3d"

[observability]
enabled = true
