# Cloudflare Pages configuration
name = "fysp-dev-website"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]


# Cloudflare Workers AI binding
[ai]
binding = "AI"

[vars]
ENABLED_PROJECTS = "3d,ai,data" # default/fallback
ENABLED_PROJECT_DEMOS = "3d,ai" # default/fallback

[env.preview.vars]
ENABLED_PROJECTS = "3d,ai,blockchain"
ENABLED_PROJECT_DEMOS = "3d,ai"

[env.production.vars]
ENABLED_PROJECTS = "3d,ai"
ENABLED_PROJECT_DEMOS = "3d"

[observability]
enabled = true
