# Cloudflare Pages configuration
name = "fysp-dev-website"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat_v2"]

# Pages configuration
pages_build_output_dir = "dist"

# Cloudflare Workers AI binding
[ai]
binding = "AI"


[vars]
ENABLED_PROJECTS = "3d,ai,data" # default/fallback
PUBLIC_ENABLED_PROJECT_DEMOS = "3d,ai" # default/fallback

[env.preview.vars]
ENABLED_PROJECTS = "3d,ai,blockchain"
PUBLIC_ENABLED_PROJECT_DEMOS = "3d,ai"

[env.production.vars]
ENABLED_PROJECTS = "3d,ai"
PUBLIC_ENABLED_PROJECT_DEMOS = "3d"
