# Cloudflare Pages configuration
name = "fysp-dev-website"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat_v2"]

# Pages configuration
pages_build_output_dir = "dist"

# Cloudflare Workers AI binding
[ai]
binding = "AI"


[vars]
ENABLED_PROJECTS = "3d" # default/fallback

[env.preview.vars]
ENABLED_PROJECTS = "3d,ai,blockchain"

[env.production.vars]
ENABLED_PROJECTS = "3d,ai"
