name: Lint (On Pull Requests)

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          node-version: 20
          pnpm-version: 9

      - name: Run Type Check
        run: pnpm run type-check
      - name: Run Lint
        run: pnpm run lint
